[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha6"

[[dependency]]
org = "ballerina"
name = "url"
version = "1.1.0-alpha6"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha6"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "0.10.0-alpha6"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.8.0-alpha6"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.0.0-alpha6"

[[dependency]]
org = "ballerina"
name = "test"
version = "0.0.0"


