[package]
org= "ballerinax"
name= "googleapis.calendar"
version= "2.0.0"
export= ["googleapis.calendar", "googleapis.calendar.listener"]
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Productivity/Calendars", "Cost/Free", "Vendor/Google"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.calendar"

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-0.1.6-SNAPSHOT.jar"
groupId = "org.ballerinalang.googleapis.calendar"
artifactId = "java-wrapper"
version = "0.1.6-SNAPSHOT"
